### ISSUE TITLE
XLS Filetype is not working

### ISSUE THREAD

**Issue by bretanac93** [matecat/MateCat-Win-Converter#2]
@giusilvano the following issue is reposted from `Matecat` repository.

Hi people, I'm currently stuck with the Additional filters, I already managed to set up a Windows server with Microsoft Office 2016 + Licenses, Visual Studio for compiling the Additional Filters C# Application and is working properly for doc and ppt documents, the mess comes with xls, when I upload a xls document, it gets forwarded to the additional filters server, here are screenshots for better understanding:

When I upload the file I receive "Bad Request" from Additional Filters:
![40003923-d2682e7a-5794-11e8-80cf-faec139eaecc](https://user-images.githubusercontent.com/3768876/40223185-79a5cebe-5a82-11e8-9f08-e7c53b59778a.png)

And this is the stdout from the Windows Server VM:

![40004025-16aba616-5795-11e8-8246-ff7ec9de82f9](https://user-images.githubusercontent.com/3768876/40223194-83175cd8-5a82-11e8-94b4-4a7aca9e397d.png)

Of course when I check the logs, what I received is the error 400 from Matecat Additional Filters server.
Thanks in advanced.

**Comment by giusilvano** [comment]
Hi @bretanac93,
Looks like the Excel instance is failing to save the converted file.
It never happened to us, and since it's an Office internal error it's harder to reproduce.
But I found this page on the MSDN that maybe can be helpful: https://goo.gl/agXaki
It says that this error is caused by a path longer than 255 characters.
Can you check your CachePath param in the App.config file? Maybe that path is long, causing the Excel exception.

**Comment by bretanac93** [comment]
ok @giusilvano I'll work on that, thanks for taking the time to answer this question.
